### ISSUE TITLE
glm.predict not available for R version 3.2.2

### ISSUE THREAD

**Issue by kpdavi** [benjaminschlegel/glm.predict#1]
Hello,

I sincerely apologize if I'm missing something obvious, but I tried installing the glm.predict package in R version 3.2.2 and it says the package is not available. When I looked at the description of the package it looked as though it should be available in versions after 3.1. Will this package become available with R version 3.2.2?

Thank you!

**Comment by benjaminschlegel** [comment]
Hi

You have to download the package with devtools. Ist not available with CRAN. See https://benjaminschlegel.ch/r/glm.predict/ on how to install it.

(There are still some problems with the discrete.changes function. It sometimes doesn’t callculate all combinations, however the values are correct. discrete.change and ordinal_discrete_change work without any problems.)

Greetings

Benjamin

Von: kpdavi [mailto:notifications@github.com] 
Gesendet: Dienstag, 15. Dezember 2015 21:07
An: benjaminschlegel/glm.predict glm.predict@noreply.github.com
Betreff: [glm.predict] glm.predict not available for R version 3.2.2 (#1)

Hello,

I sincerely apologize if I'm missing something obvious, but I tried installing the glmpredict package in R version 322 and it says the package is not available When I looked at the description of the package it looked as though it should be available in versions after 31 Will this package become available with R version 322?

Thank you!
